functional:
  - Сайт должен иметь возможность регистрации пользователей
  - Сайт должен уметь создавать игровые сессии между игроками
  - Сайт должен предоставлять игрокам информацию о процессе написания кода публично и в реальном времени
  - Пользователи должны иметь возможность создавать игру с ботом
  - Сайт должен иметь возможность отображать рейтинг всех игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Таблица рейтинга должна иметь внутренюю фильтрацию по уровню, проценту побед и/или поражений и т.д.
  - Пользователи должны иметь возможность гибкой настройки профиля
  - У сайта должна быть возможность изменения языка как без регистрации, так и в настройках профиля
  
