functional:
  - Сайт должен иметь возможность регистрации пользователей
  - Сайт должен иметь возможность авторизации пользователей
  - Пользователь должен иметь возможность выбирать язык игры
  - Пользователи должны иметь возможность создавать игру с ботом
  - Пользователи должны иметь возможность создавать игровые сессии с другими пользователями
  - Сайт должен предоставлять обоим игрокам информацию о процессе написания кода публично и в реальном времени
  - Сайт должен уметь проверять код игроков
  - Пользователь должен иметь возможность закончить игру досрочно
  - Сайт должен отображать рейтинг всех игроков за разные промежутки времени
  - Сайт должен отображать игроков, находящихся в сети в режиме реального времени

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
  - Таблица рейтинга должна иметь внутренюю фильтрацию по уровню, проценту побед и/или поражений и т.д.
  - Пользователь не может редактировать свой рейтинг
  - Пользователь не может менять код своего соперника в процессе игры
  - У сайта должна быть возможность изменения языка с английского на русский и наоборот как без регистрации, так и в настройках профиля при авторизации
